#!/usr/bin/env bash

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles
export FONT="Hack Nerd Font"
export LOADING_ICON=􀖇
export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
    height=27
    color="$BACKGROUND"
    border_width=0
    shadow=off
    position=bottom
    sticky=on
    padding_right=0
    padding_left=0
    y_offset=0
    margin=0
    topmost=window
)
sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

defaults=(
    icon.font="Agave Nerd Font:Bold:20"
    icon.color="$FOREGROUND"
    icon.padding_left=4
    icon.padding_right=4
    label.font="$FONT:Bold:14"
    label.color="$FOREGROUND"
    label.padding_left=5
    label.padding_right=5
    background.height=27
    background.color="$TRANSPARENT"
    background.corner_radius=0
    background.border_width=0
    background.padding_left=4
    background.padding_right=4
    popup.icon.font.size=100
    popup.icon.font.family="$FONT"
    popup.icon.font.size=30
    popup.icon.padding_right=10
    popup.label.font.size=30
    popup.padding_left=7
    popup.padding_right=7
    popup.background.corner_radius=12
    popup.icon.padding_right=100
    popup.background.border_width=2
    popup.background.corner_radius=6
    popup.background.border_color="$BACKGROUND_ALT"
    popup.background.color="$BACKGROUND"
    popup.blur_radius=20
    popup.background.shadow.drawing=off
)
sketchybar --default "${defaults[@]}"

##### Adding Mission Control Space Indicators #####
# Now we add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces


# Parts outside of big colored part.
# Right
source "$ITEM_DIR/brew.sh"
source "$ITEM_DIR/github.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"

# Addings spaces and big colored part.
# Left
source "$ITEM_DIR/spaces.sh"

# Adding items on top of big colored part.
# Left
source "$ITEM_DIR/windows.sh"
source "$ITEM_DIR/front_app.sh"
# Right

sketchybar --hotload on

# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.
sketchybar --update
sketchybar --trigger windows_on_spaces focus_space # to ensure icons are showing on reload
