[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[shell]
program = "bash"

[window]
opacity = 1
option_as_alt = "Both"
title = "Ruud's alacritty"

[cursor.style]
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"
