## Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Utilities.

# source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
#
# source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"
ZSH_CUSTOM="$HOME/.dotfiles/shell/zsh_custom"
# plugins=(git zsh-autosuggestions zsh-syntax-highlighting fast-syntax-highlighting zsh-autocomplete)
plugins=(git zsh-autosuggestions zsh-syntax-highlighting  zsh-autocomplete)
# plugins=(git fast-syntax-highlighting) 
source "$ZSH/oh-my-zsh.sh"

eval "$(zoxide init zsh)"

# Alias definitions.
if [ -f ~/.shell_aliases ] || [ -L ~/.shell_aliases ]; then
	. ~/.shell_aliases
fi

# Aliases, adding to PATH, etc., that only need to be done on this specific OS.
if [ -f ~/.shell_osspecific ] || [ -L ~/.shell_osspecific ]; then
	. ~/.shell_osspecific
fi

# Non-public exports, aliases, etc.
if [ -f ~/.shell_secrets ] || [ -L ~/.shell_secrets ]; then
	. ~/.shell_secrets
fi

# Keybindings.
autoload -Uz up-line-or-search
autoload -Uz down-line-or-search

bindkey '^P' up-line-or-search     # Ctrl-P
bindkey '^N' down-line-or-search   # Ctrl-N
bindkey '^Y' accept-line           # Ctrl-Y



# Prompt style.

# (to customize prompt, run `p10k configure` or edit ~/.p10k.zsh.)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# For windows machines: ensure scoop called on powershell x86
scoop() {
    "/c/Windows/SysWOW64/WindowsPowerShell/v1.0/powershell.exe" -NoProfile -ExecutionPolicy RemoteSigned -Command scoop "$@"
}

# Message so I know it worked
# (disabled because p10k is complaining)
# echo "successfully loaded Ruud Wijtvliet zsh user profile"
