# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export PATH="/opt/homebrew/bin/:$PATH"

# Utilities.

source /opt/homebrew/share/powerlevel10k/powerlevel9k.zsh-theme
# (to customize prompt, run `p10k configure` or edit ~/.p10k.zsh.)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

eval "$(zoxide init zsh)"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.sh_aliases ] || [ -L ~/.sh_aliases ]; then
	. ~/.sh_aliases
fi

# Aliases, adding to PATH, etc., that only need to be done on this specific OS.
if [ -f ~/.sh_osspecific ] || [ -L ~/.sh_osspecific ]; then
	. ~/.sh_osspecific
fi

# Non-public exports, aliases, etc.
if [ -f ~/.sh_secrets ] || [ -L ~/.sh_secrets ]; then
	. ~/.sh_secrets
fi

# message so I know it worked
# echo "successfully loaded Ruud Wijtvliet zsh user profile"
