return {
  --   config = function()
  --
  --     local actions = require "telescope.actions"
  --     return {
  --       pickers = {find_files = {follow = true, hidden = true}},
  --       mappings = {
  --         i = {
  --
  --         },
  --         n = {
  --          ["t"] = actions.move_selection_previous,
  --           ["n"] = actions.move_selection_next,
  --         }
  --       }
  --     }
  --   end
  -- }
  -- You can also add new plugins here as well:
  -- Add plugins, the lazy syntax
  -- "andweeb/presence.nvim",
  -- {
  --   "ray-x/lsp_signature.nvim",
  --   event = "BufRead",
  --   config = function()
  --     require("lsp_signature").setup()
  --   end,
  -- },
}
