#!/usr/bin/env bash

# Unfortunately it's not easy to directly use Polybar colour values in this
# script so I have to redefine some of my colours here. See the link below for
# more details:
# https://github.com/polybar/polybar/wiki/Formatting#format-tags-inside-polybar-config
green=#55aa55

CONFIG=ruudxps20


connect() {
    sudo wg-quick up "$CONFIG"
}

disconnect() {
    sudo wg-quick down "$CONFIG"
}

connected_interfaces() {
    echo $(networkctl | grep wireguard | cut -d " " -f4)
}

toggle() {
    ci=$(connected_interfaces)
    if [[ $ci ]]; then
        disconnect
    else
        connect
    fi
}

print() {
    ci=$(connected_interfaces)
    if [[ $ci ]]; then
        echo %{u"$green"}%{+u}%{T4}%{F"$green"}%{T-}%{F-} "$ci"
    else
        echo %{T4}%{T-}
    fi
}

case "$1" in
    --connect)
        connect
        ;;
    --disconnect)
        disconnect
        ;;
    --toggle)
        toggle
        ;;
    *)
        print
        ;;
esac
