#!/usr/bin/env bash
# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


# Mission-control spaces
/usr/local/bin/yabpy prepare-spaces


# Window rules

# windows to ignore
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility|System Settings)$" manage=off
yabai -m rule --add app="^mpv$" manage=off sticky=on layer=above opacity=1.0 grid=8:8:6:0:2:2
yabai -m rule --add title="(Reminder|Reminders|Notification|Notifications|Preferences|Settings)$" manage=off sticky=on opacity=0.9
yabai -m rule --add title="^(Share|Confirm)" manage=off sticky=on layer=above opacity=0.9

# assign to space
yabai -m rule --add app="^Finder$" space=^1_files # use label incase order is changed (i.e., by moving space to other monitor)
yabai -m rule --add app="^Firefox$" space=^2_www
# yabai -m rule --add app="^Alacritty$" space=^4_terminal # alacritty can be opened everywhere
yabai -m rule --add app="^Microsoft Teams (work or school)$" space=^7_teams
yabai -m rule --add app="^Microsoft Outlook$" space=^8_email
yabai -m rule --add app="^Spotify$" space=9_media


# Signals

# defaults by yabai
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
yabai -m signal --add event=window_minimized active=yes action="if \$(yabai -m query --windows --window \$YABAI_WINDOW_ID | jq -r '.\"is-floating\"'); then yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null; fi"

# sketchybar
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"



# specific space settings
# yabai -m config --space mail  layout stack


# global settings
# window-topmost must be off, otherwise pop-up windows hide behind main window
yabai -m config                              \
    external_bar                all:0:27     \
    mouse_follows_focus         off          \
    focus_follows_mouse         off          \
    window_placement            second_child \
    window_shadow               off          \
    window_animation_duration   0.0          \
    window_opacity_duration     0.0          \
    window_opacity              on           \
    active_window_opacity       1.00         \
    normal_window_opacity       0.75         \
    insert_feedback_color       0xaad75f5f   \
    split_ratio                 0.55         \
    split_type                  auto         \
    auto_balance                off          \
    top_padding                 10           \
    left_padding                10           \
    right_padding               10           \
    bottom_padding              10           \
    window_gap                  10           \
    layout                      bsp          \
    mouse_modifier              fn           \
    mouse_action1               move         \
    mouse_action2               resize       \
    mouse_drop_action           swap

brew services start sketchybar

sleep 10  # sleep to see if it helps sketchybar/yabai recognise the apps launched below

# Apps to start

open "/Applications/Firefox.app"

echo "yabai configuration loaded.."
